# Generated by Django 4.0.1 on 2022-01-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='CPF'),
        ),
    ]
