# Generated by Django 4.0.1 on 2022-01-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(error_messages={'unique': 'Nome já cadastrado.'}, max_length=255, unique=True, verbose_name='Nome')),
                ('cnpj', models.CharField(error_messages={'unique': 'CNPJ já cadastrado!'}, max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(error_messages={'unique': 'Email já cadastrado.'}, max_length=255, unique=True, verbose_name='Email')),
                ('status', models.CharField(max_length=15, verbose_name='ativo')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
            ],
            options={
                'verbose_name_plural': 'Companhias',
            },
        ),
    ]
